### ISSUE TITLE
Grid between art tiles?

### ISSUE THREAD

**Issue by welovekyo** [beetlebob/beetlebob.github.io#2]
![screen shot 2016-10-02 at 1 02 48 am](https://cloud.githubusercontent.com/assets/22566030/19019017/05923068-883c-11e6-8233-c8c6974d126f.png)

Is there a way for us to build out grids so that all drawings live in tiles that are equal spacings from each other?

OR is it because my files aren't sized consistently? Let me know and I can update that on my end.

Thanks!

**Comment by rbonick** [comment]
I can add some spacing above / below each row, that's my fault! It won't be perfectly even if the images are different sizes but I wouldn't worry about it too much.

**Comment by welovekyo** [comment]
you are amazing, thank you! it looks so good
