### ISSUE TITLE
NOT URGENT: Google Analytics tracking ID

### ISSUE THREAD

**Issue by welovekyo** [beetlebob/beetlebob.github.io#3]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-85052092-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by rbonick** [comment]
So if you set up Google Analytics and get me the embed code, I can add it very quickly. But it's better if you set it up =D

**Comment by welovekyo** [comment]
oops thought i had sent through the codes haha lmk if this is what youre looking for...

UPDATE: will send you the codes through FB, everytime i paste the code in this comment section it disappears lol
