### ISSUE TITLE
creating new sections (aka aboutme)

### ISSUE THREAD

**Issue by welovekyo** [beetlebob/beetlebob.github.io#4]
soooo, tried to build out another section, section (about me) worked. but the image i loaded in is corrupt when i click on it?

![capture](https://cloud.githubusercontent.com/assets/22566030/19708874/94506a8c-9ae7-11e6-9f04-40cf812e1bb4.PNG)

let me know what section i need to adjust because i will likely make some shifts to the layout anyways lol

**Comment by welovekyo** [comment]
also, what if i want this page's layout to be not tile form, but more so one photo and text?

**Comment by welovekyo** [comment]
also would like to be able to add instagram icon to gain followers?

**Comment by rbonick** [comment]
Gonna bump the instagram icon out to its own issue.

**Comment by welovekyo** [comment]
also, created a big cartel link to be dropped into
