### ISSUE TITLE
shop button - not urgent

### ISSUE THREAD

**Issue by welovekyo** [beetlebob/beetlebob.github.io#6]
create shop buttons, but leave URL blank to be updated with potentially etsy links? that would look more profesh

if not, can also include link in "comment/description" section

**Comment by rbonick** [comment]
Yeah, let's figure out if we can find a good way to display shop links on the main page, otherwise we can totally do description section.

**Comment by welovekyo** [comment]
i created a big cartel link, is there any way to just link a shop button to this page?

http://beetlebob.bigcartel.com

THANK YOU!
