### ISSUE TITLE
Tile order??       Side question (not so much an issue) more so a question

### ISSUE THREAD

**Issue by welovekyo** [beetlebob/beetlebob.github.io#8]
How can i adjust the tile orders? it looks like currently it is pulling alphabetically by what i name the _designs.md

If not, i think i can work around it by adding #s in front of the name. but want to confirm that is the best way to do it

1.aboutme.md
2.catch.md 

etc

**Comment by rbonick** [comment]
Yup it's alphabetical. Would suggest 3-4 digits though (001, 002, 003) as most alphabetical sorts don't handle numbers correctly (e.g. 12 comes before 2)

**Comment by welovekyo** [comment]
ok smart that is a good idea, i will do that!
